name: Rommel Automation Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Code checkout
      - uses: actions/checkout@v4

      # Java config JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'
          cache: maven

      # (Chrome y Firefox)
      - name: Install browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl
          # Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install
          # Firefox
          sudo apt-get install -y firefox

      # Tests execution
      - name: Run Selenium tests
        run: mvn verify -Dbrowser=chrome_headless

      # Uploading the test reports as an artifact
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: target/docs

      # Create .nojekyll file to disable Jekyll processing
      - name: Disable Jekyll
        run: touch target/docs/.nojekyll

      # Publishing Report in GitHub Pages
      - name: Deploy Cucumber reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/docs